// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'category',
      label: 'Peridio Core',
      items: [
        {
          type: 'autogenerated',
          dirName: 'peridio-core',
        },
      ],
    },
    {
      type: 'category',
      label: 'Policies',
      items: [
        {
          type: 'autogenerated',
          dirName: 'policies',
        },
      ],
    },
  ],
}

export default sidebars
